import Foundation

struct HelixModelInfo {
    let category: String
    let name: String
}

enum HelixModelCatalog {
    static let models: [String: HelixModelInfo] = [
        "00": HelixModelInfo(category: "Amp", name: "Cali 400 Ch1 (mono)"),
        "01": HelixModelInfo(category: "Amp", name: "Cali 400 Ch2 (mono)"),
        "02": HelixModelInfo(category: "Amp", name: "Cali Bass (mono)"),
        "03": HelixModelInfo(category: "Amp", name: "G Cougar 800 (mono)"),
        "04": HelixModelInfo(category: "Amp", name: "Ampeg SVT Brt Bass Ampeg SVT (bright channel) (mono)"),
        "05": HelixModelInfo(category: "Amp", name: "Ampeg SVT Nrm Bass Ampeg SVT (normal channel) (mono)"),
        "06": HelixModelInfo(category: "Amp", name: "Ampeg B-15NF Bass Ampeg B-15NF Portaflex (mono)"),
        "07": HelixModelInfo(category: "Amp", name: "A30 Fawn Brt Guitar Vox AC-30 Fawn (bright channel) (mono)"),
        "08": HelixModelInfo(category: "Amp", name: "A30 Fawn Nrm Guitar Vox AC-30 Fawn (normal channel) (mono)"),
        "09": HelixModelInfo(category: "Amp", name: "ANGL Meteor Guitar ENGL Fireball 100 (mono)"),
        "0a": HelixModelInfo(category: "Amp", name: "Brit 2204 Guitar Marshall JCM-800 (mono)"),
        "0b": HelixModelInfo(category: "Amp", name: "Brit J45 Brt Guitar Marshall JTM-45 (bright channel) (mono)"),
        "0c": HelixModelInfo(category: "Amp", name: "Brit J45 Nrm Guitar Marshall JTM-45 (normal channel) (mono)"),
        "0d": HelixModelInfo(category: "Amp", name: "Brit P75 Brt Guitar Park 75 (bright channel) (mono)"),
        "0e": HelixModelInfo(category: "Amp", name: "Brit P75 Nrm Guitar Park 75 (normal channel) (mono)"),
        "0f": HelixModelInfo(category: "Amp", name: "Brit Plexi Brt Guitar Marshall Super Lead 100 (bright channel) (mono)"),
        "10": HelixModelInfo(category: "Amp", name: "Brit Plexi Jump Guitar Marshall Super Lead 100 (jumped) (mono)"),
        "11": HelixModelInfo(category: "Amp", name: "Brit Plexi Nrm Guitar Marshall Super Lead 100 (normal channel) (mono)"),
        "12": HelixModelInfo(category: "Amp", name: "Cali Rectifire Guitar MESA/Boogie Dual Rectifier (mono)"),
        "13": HelixModelInfo(category: "Amp", name: "Divided Duo Guitar 13 JRT 9/15 (mono)"),
        "14": HelixModelInfo(category: "Amp", name: "Essex A15 Guitar Vox AC-15 (mono)"),
        "15": HelixModelInfo(category: "Amp", name: "Essex A30 Guitar Vox AC-30 with top boost (mono)"),
        "16": HelixModelInfo(category: "Amp", name: "German Mahadeva Guitar Bogner Shiva (mono)"),
        "17": HelixModelInfo(category: "Amp", name: "German Ubersonic Guitar Bogner Ueberschall  (mono)"),
        "18": HelixModelInfo(category: "Amp", name: "Interstate Zed Guitar Dr Z Route 66 (mono)"),
        "19": HelixModelInfo(category: "Amp", name: "Jazz Rivet 120 Guitar Roland JC-120 Jazz Chorus (mono)"),
        "1a": HelixModelInfo(category: "Amp", name: "Line 6 Doom Guitar Line 6 Original (mono)"),
        "1b": HelixModelInfo(category: "Amp", name: "Line 6 Elektrik Guitar Line 6 Original (mono)"),
        "1c": HelixModelInfo(category: "Amp", name: "Line 6 Epic Guitar Line 6 Original (mono)"),
        "1d": HelixModelInfo(category: "Amp", name: "Mail Order Twin Guitar Silvertone 1484 (mono)"),
        "1e": HelixModelInfo(category: "Amp", name: "Mandarin 80 Guitar Orange OR80 (mono)"),
        "1f": HelixModelInfo(category: "Amp", name: "PV Panama Guitar Peavey 5150 (mono)"),
        "20": HelixModelInfo(category: "Amp", name: "Solo Lead Clean Guitar Soldano SLO-100 (clean channel) (mono)"),
        "21": HelixModelInfo(category: "Amp", name: "Solo Lead Crunch Guitar Soldano SLO-100 (crunch channel) (mono)"),
        "22": HelixModelInfo(category: "Amp", name: "Solo Lead OD Guitar Soldano SLO-100 (overdrive channel) (mono)"),
        "23": HelixModelInfo(category: "Amp", name: "Soup Pro (mono)"),
        "24": HelixModelInfo(category: "Amp", name: "Stone Age 185 (mono)"),
        "25": HelixModelInfo(category: "Amp", name: "Tweed Blues Brt (mono)"),
        "26": HelixModelInfo(category: "Amp", name: "Tweed Blues Nrm (mono)"),
        "27": HelixModelInfo(category: "Amp", name: "US Deluxe Nrm (mono)"),
        "28": HelixModelInfo(category: "Amp", name: "US Deluxe Vib (mono)"),
        "29": HelixModelInfo(category: "Amp", name: "US Double Nrm (mono)"),
        "2a": HelixModelInfo(category: "Amp", name: "US Double Vib (mono)"),
        "2b": HelixModelInfo(category: "Amp", name: "US Small Tweed (mono)"),
        "2c": HelixModelInfo(category: "Amp", name: "WhoWatt 100 (mono)"),
        "2d": HelixModelInfo(category: "Cab", name: "1x12 Blue Bell Single, Dual 1x12\" Vox AC-15 Blue (mono)"),
        "2e": HelixModelInfo(category: "Cab", name: "1x12 Celest 12H Single, Dual 1x12\" 13 JRT 9/15 G12 H30 (mono)"),
        "2f": HelixModelInfo(category: "Cab", name: "1x12 Field Coil Single, Dual 1x12\" Gibson EH185 (mono)"),
        "30": HelixModelInfo(category: "Cab", name: "1x12 Lead 80 Single, Dual 1x12\" Bogner Shiva CL80 (mono)"),
        "31": HelixModelInfo(category: "Cab", name: "1x12 US Deluxe Single, Dual 1x12\" Fender Deluxe Oxford (mono)"),
        "32": HelixModelInfo(category: "Cab", name: "1x15 Ampeg B-15  (mono)"),
        "33": HelixModelInfo(category: "Cab", name: "Soup Pro Ellipse Single, Dual 1 x 6x9\" Supro S6616 (mono)"),
        "34": HelixModelInfo(category: "Cab", name: "1x8 Small Tweed Single, Dual 1x8\" Fender Champ (mono)"),
        "35": HelixModelInfo(category: "Cab", name: "2x12 Blue Bell Single, Dual 2x12\" Vox AC-30 Fawn Blue (mono)"),
        "36": HelixModelInfo(category: "Cab", name: "2x12 Double C12N Single, Dual 2x12\" Fender Twin C12N (mono)"),
        "37": HelixModelInfo(category: "Cab", name: "2x12 Interstate Single, Dual 2x12\" Dr Z Z Best V30 (mono)"),
        "38": HelixModelInfo(category: "Cab", name: "2x12 Jazz Rivet Single, Dual 2x12\" Roland JC-120 (mono)"),
        "39": HelixModelInfo(category: "Cab", name: "2x12 Mail C12Q Single, Dual 2x12\" Silvertone 1484 (mono)"),
        "3a": HelixModelInfo(category: "Cab", name: "2x12 Silver Bell Single, Dual 2x12\" Vox AC-30TB Silver (mono)"),
        "3b": HelixModelInfo(category: "Cab", name: "2x15 Brute (mono)"),
        "3c": HelixModelInfo(category: "Cab", name: "4x10 Ampeg HLF  (mono)"),
        "3d": HelixModelInfo(category: "Cab", name: "4x10 Tweed P10R Single, Dual 4x10\" Fender Bassman P10R (mono)"),
        "3e": HelixModelInfo(category: "Cab", name: "4x12 1960 T75 Single, Dual 4x12\" Marshall 1960 AT75 (mono)"),
        "3f": HelixModelInfo(category: "Cab", name: "4x12 Blackback30 Single, Dual 4x12\" Park 75 G12 H30 (mono)"),
        "40": HelixModelInfo(category: "Cab", name: "4x12 Cali V30 (mono)"),
        "41": HelixModelInfo(category: "Cab", name: "4x12 Greenback20 Single, Dual 4x12\" Marshall Basketweave G12 M20 (mono)"),
        "42": HelixModelInfo(category: "Cab", name: "4x12 Greenback25 Single, Dual 4x12\" Marshall Basketweave G12 M25 (mono)"),
        "43": HelixModelInfo(category: "Cab", name: "4x12 Mandarin EM Single, Dual 4x12\" Orange Eminence (mono)"),
        "44": HelixModelInfo(category: "Cab", name: "4x12 SoloLead EM  (mono)"),
        "45": HelixModelInfo(category: "Cab", name: "4x12 Uber T75 Single, Dual 4x12\" Bogner Uberkab T75 (mono)"),
        "46": HelixModelInfo(category: "Cab", name: "4x12 Uber V30 Single, Dual 4x12\" Bogner Uberkab V30 (mono)"),
        "47": HelixModelInfo(category: "Cab", name: "4x12 WhoWatt 100 Single, Dual 4x12\" Hiwatt AP Fane (mono)"),
        "48": HelixModelInfo(category: "Cab", name: "4x12 XXL V30 (mono)"),
        "49": HelixModelInfo(category: "Cab", name: "6x10 Cali Power  (mono)"),
        "4a": HelixModelInfo(category: "Cab", name: "8x10 Ampeg SVT E (mono)"),
        "4b": HelixModelInfo(category: "Delay", name: "Adriatic Delay Mono, Stereo BOSS DM-2 w/ Adrian Mod (mono)"),
        "4c": HelixModelInfo(category: "Delay", name: "Bucket Brigade Mono, Stereo BOSS DM-2 (mono)"),
        "4d": HelixModelInfo(category: "Delay", name: "Ducked Delay Mono, Stereo TC Electronic 2290 (mono)"),
        "4e": HelixModelInfo(category: "Delay", name: "Elephant Man Mono, Stereo Electro-Harmonix Deluxe Memory Man (mono)"),
        "4f": HelixModelInfo(category: "Delay", name: "Mod/Chorus Echo Mono, Stereo Line 6 Original (mono)"),
        "50": HelixModelInfo(category: "Delay", name: "Simple Delay Mono, Stereo Line 6 Original (mono)"),
        "51": HelixModelInfo(category: "Delay", name: "Sweep Echo Mono, Stereo Line 6 Original (mono)"),
        "52": HelixModelInfo(category: "Delay", name: "Transistor Tape Mono, Stereo Maestro Echoplex EP-3 (mono)"),
        "53": HelixModelInfo(category: "Delay", name: "Adriatic Delay Mono, Stereo BOSS DM-2 w/ Adrian Mod (stereo)"),
        "54": HelixModelInfo(category: "Delay", name: "Bucket Brigade Mono, Stereo BOSS DM-2 (stereo)"),
        "55": HelixModelInfo(category: "Delay", name: "Ducked Delay Mono, Stereo TC Electronic 2290 (stereo)"),
        "56": HelixModelInfo(category: "Delay", name: "Elephant Man Mono, Stereo Electro-Harmonix Deluxe Memory Man (stereo)"),
        "57": HelixModelInfo(category: "Delay", name: "Harmony Delay  (stereo)"),
        "58": HelixModelInfo(category: "Delay", name: "Mod/Chorus Echo Mono, Stereo Line 6 Original (stereo)"),
        "59": HelixModelInfo(category: "Delay", name: "Multitap 4  (stereo)"),
        "5a": HelixModelInfo(category: "Delay", name: "Multitap 6  (stereo)"),
        "5b": HelixModelInfo(category: "Delay", name: "Ping Pong  (stereo)"),
        "5c": HelixModelInfo(category: "Delay", name: "Simple Delay Mono, Stereo Line 6 Original (stereo)"),
        "5d": HelixModelInfo(category: "Delay", name: "Sweep Echo Mono, Stereo Line 6 Original (stereo)"),
        "5e": HelixModelInfo(category: "Delay", name: "Transistor Tape Mono, Stereo Maestro Echoplex EP-3 (stereo)"),
        "5f": HelixModelInfo(category: "Distortion", name: "Arbitrator Fuzz Mono, Stereo Arbiter FuzzFace (mono)"),
        "60": HelixModelInfo(category: "Distortion", name: "Compulsive Drive (mono)"),
        "61": HelixModelInfo(category: "Distortion", name: "Hedgehog D9 (mono)"),
        "62": HelixModelInfo(category: "Distortion", name: "Industrial Fuzz Mono, Stereo Z.Vex Fuzz Factory (mono)"),
        "63": HelixModelInfo(category: "Distortion", name: "Megaphone Mono, Stereo Megaphone (mono)"),
        "64": HelixModelInfo(category: "Distortion", name: "Minotaur (mono)"),
        "65": HelixModelInfo(category: "Distortion", name: "Scream 808 (mono)"),
        "66": HelixModelInfo(category: "Distortion", name: "Top Secret OD (mono)"),
        "67": HelixModelInfo(category: "Distortion", name: "Triangle Fuzz Mono, Stereo Electro-Harmonix Big Muff Pi (mono)"),
        "68": HelixModelInfo(category: "Distortion", name: "Tycoctavia Fuzz Mono, Stereo Tycobrahe Octavia (mono)"),
        "69": HelixModelInfo(category: "Distortion", name: "Valve Driver (mono)"),
        "6a": HelixModelInfo(category: "Distortion", name: "Vermin Dist Mono, Stereo Pro Co RAT (mono)"),
        "6b": HelixModelInfo(category: "Distortion", name: "Arbitrator Fuzz Mono, Stereo Arbiter FuzzFace (stereo)"),
        "6c": HelixModelInfo(category: "Distortion", name: "Compulsive Drive (stereo)"),
        "6d": HelixModelInfo(category: "Distortion", name: "Hedgehog D9 (stereo)"),
        "6e": HelixModelInfo(category: "Distortion", name: "Industrial Fuzz Mono, Stereo Z.Vex Fuzz Factory (stereo)"),
        "6f": HelixModelInfo(category: "Distortion", name: "Megaphone Mono, Stereo Megaphone (stereo)"),
        "70": HelixModelInfo(category: "Distortion", name: "Minotaur (stereo)"),
        "71": HelixModelInfo(category: "Distortion", name: "Scream 808 (stereo)"),
        "72": HelixModelInfo(category: "Distortion", name: "Top Secret OD (stereo)"),
        "73": HelixModelInfo(category: "Distortion", name: "Triangle Fuzz Mono, Stereo Electro-Harmonix Big Muff Pi (stereo)"),
        "74": HelixModelInfo(category: "Distortion", name: "Tycoctavia Fuzz Mono, Stereo Tycobrahe Octavia (stereo)"),
        "75": HelixModelInfo(category: "Distortion", name: "Valve Driver (stereo)"),
        "76": HelixModelInfo(category: "Distortion", name: "Vermin Dist Mono, Stereo Pro Co RAT (stereo)"),
        "77": HelixModelInfo(category: "Dynamic", name: "Deluxe Comp (mono)"),
        "78": HelixModelInfo(category: "Dynamic", name: "LA Studio Comp (mono)"),
        "79": HelixModelInfo(category: "Dynamic", name: "Red Squeeze (mono)"),
        "7a": HelixModelInfo(category: "Dynamic", name: "Hard Gate (mono)"),
        "7b": HelixModelInfo(category: "Dynamic", name: "Noise Gate (mono)"),
        "7c": HelixModelInfo(category: "Dynamic", name: "Deluxe Comp (stereo)"),
        "7d": HelixModelInfo(category: "Dynamic", name: "LA Studio Comp (stereo)"),
        "7e": HelixModelInfo(category: "Dynamic", name: "Red Squeeze (stereo)"),
        "7f": HelixModelInfo(category: "Dynamic", name: "Hard Gate (stereo)"),
        "cc80": HelixModelInfo(category: "Dynamic", name: "Noise Gate (stereo)"),
        "cc81": HelixModelInfo(category: "EQ", name: "10 Band Graphic (mono)"),
        "cc82": HelixModelInfo(category: "EQ", name: "Low and High Cut (mono)"),
        "cc83": HelixModelInfo(category: "EQ", name: "Parametric (mono)"),
        "cc84": HelixModelInfo(category: "EQ", name: "Simple EQ (mono)"),
        "cc85": HelixModelInfo(category: "EQ", name: "10 Band Graphic (stereo)"),
        "cc86": HelixModelInfo(category: "EQ", name: "Low and High Cut (stereo)"),
        "cc87": HelixModelInfo(category: "EQ", name: "Parametric (stereo)"),
        "cc88": HelixModelInfo(category: "EQ", name: "Simple EQ (stereo)"),
        "cc89": HelixModelInfo(category: "Filter", name: "Mutant Filter (mono)"),
        "cc8a": HelixModelInfo(category: "Filter", name: "Mystery Filter (mono)"),
        "cc8b": HelixModelInfo(category: "Filter", name: "Mutant Filter (stereo)"),
        "cc8c": HelixModelInfo(category: "Filter", name: "Mystery Filter (stereo)"),
        "cc8d": HelixModelInfo(category: "Send/Return", name: "Return R (mono)"),
        "cc8e": HelixModelInfo(category: "Send/Return", name: "FX Loop L (mono)"),
        "cc91": HelixModelInfo(category: "Send/Return", name: "Return L/R (stereo)"),
        "cc95": HelixModelInfo(category: "Impulse Response", name: "1024 samples"),
        "cc96": HelixModelInfo(category: "Impulse Response", name: "2048 samples"),
        "cc9a": HelixModelInfo(category: "Modulation", name: "70s Chorus (mono)"),
        "cc9b": HelixModelInfo(category: "Modulation", name: "Chorus (mono)"),
        "cc9c": HelixModelInfo(category: "Modulation", name: "Courtesan Flange (mono)"),
        "cc9d": HelixModelInfo(category: "Modulation", name: "Gray Flanger (mono)"),
        "cc9e": HelixModelInfo(category: "Modulation", name: "Harmonic Flanger (mono)"),
        "cc9f": HelixModelInfo(category: "Modulation", name: "Script Mod Phase (mono)"),
        "cca0": HelixModelInfo(category: "Modulation", name: "Ubiquitous Vibe (mono)"),
        "cca1": HelixModelInfo(category: "Modulation", name: "AM Ring Mod Mono, Stereo Line 6 Original (mono)"),
        "cca2": HelixModelInfo(category: "Modulation", name: "60s Bias Trem (mono)"),
        "cca3": HelixModelInfo(category: "Modulation", name: "Optical Trem (mono)"),
        "cca4": HelixModelInfo(category: "Modulation", name: "Bubble Vibrato (mono)"),
        "cca5": HelixModelInfo(category: "Modulation", name: "70s Chorus (stereo)"),
        "cca6": HelixModelInfo(category: "Modulation", name: "Chorus (stereo)"),
        "cca7": HelixModelInfo(category: "Modulation", name: "Trinity Chorus  (stereo)"),
        "cca8": HelixModelInfo(category: "Modulation", name: "Courtesan Flange (stereo)"),
        "cca9": HelixModelInfo(category: "Modulation", name: "Gray Flanger (stereo)"),
        "ccaa": HelixModelInfo(category: "Modulation", name: "Harmonic Flanger (stereo)"),
        "ccab": HelixModelInfo(category: "Modulation", name: "Script Mod Phase (stereo)"),
        "ccac": HelixModelInfo(category: "Modulation", name: "Ubiquitous Vibe (stereo)"),
        "ccad": HelixModelInfo(category: "Modulation", name: "AM Ring Mod Mono, Stereo Line 6 Original (stereo)"),
        "ccae": HelixModelInfo(category: "Modulation", name: "Pitch Ring Mod  (stereo)"),
        "ccaf": HelixModelInfo(category: "Modulation", name: "122 Rotary  (stereo)"),
        "ccb0": HelixModelInfo(category: "Modulation", name: "145 Rotary  (stereo)"),
        "ccb1": HelixModelInfo(category: "Modulation", name: "Vibe Rotary  (stereo)"),
        "ccb2": HelixModelInfo(category: "Modulation", name: "60s Bias Trem (stereo)"),
        "ccb3": HelixModelInfo(category: "Modulation", name: "Optical Trem (stereo)"),
        "ccb4": HelixModelInfo(category: "Modulation", name: "Bubble Vibrato (stereo)"),
        "ccb6": HelixModelInfo(category: "Pitch/Synth", name: "Pitch Wham (mono)"),
        "ccb7": HelixModelInfo(category: "Pitch/Synth", name: "Twin Harmony (mono)"),
        "ccb8": HelixModelInfo(category: "Pitch/Synth", name: "Pitch Wham (stereo)"),
        "ccb9": HelixModelInfo(category: "Pitch/Synth", name: "Twin Harmony (stereo)"),
        "ccba": HelixModelInfo(category: "Preamp", name: "Cali 400 Ch1 (mono)"),
        "ccbb": HelixModelInfo(category: "Preamp", name: "Cali 400 Ch2 (mono)"),
        "ccbc": HelixModelInfo(category: "Preamp", name: "Cali Bass (mono)"),
        "ccbd": HelixModelInfo(category: "Preamp", name: "G Cougar 800 (mono)"),
        "ccbe": HelixModelInfo(category: "Preamp", name: "Ampeg SVT Brt Bass Ampeg SVT (bright channel) (mono)"),
        "ccbf": HelixModelInfo(category: "Preamp", name: "Ampeg SVT Nrm Bass Ampeg SVT (normal channel) (mono)"),
        "ccc0": HelixModelInfo(category: "Preamp", name: "Ampeg B-15NF Bass Ampeg B-15NF Portaflex (mono)"),
        "ccc1": HelixModelInfo(category: "Preamp", name: "A30 Fawn Brt Guitar Vox AC-30 Fawn (bright channel) (mono)"),
        "ccc2": HelixModelInfo(category: "Preamp", name: "A30 Fawn Nrm Guitar Vox AC-30 Fawn (normal channel) (mono)"),
        "ccc3": HelixModelInfo(category: "Preamp", name: "ANGL Meteor Guitar ENGL Fireball 100 (mono)"),
        "ccc4": HelixModelInfo(category: "Preamp", name: "Brit 2204 Guitar Marshall JCM-800 (mono)"),
        "ccc5": HelixModelInfo(category: "Preamp", name: "Brit J45 Brt Guitar Marshall JTM-45 (bright channel) (mono)"),
        "ccc6": HelixModelInfo(category: "Preamp", name: "Brit J45 Nrm Guitar Marshall JTM-45 (normal channel) (mono)"),
        "ccc7": HelixModelInfo(category: "Preamp", name: "Brit P75 Brt Guitar Park 75 (bright channel) (mono)"),
        "ccc8": HelixModelInfo(category: "Preamp", name: "Brit P75 Nrm Guitar Park 75 (normal channel) (mono)"),
        "ccc9": HelixModelInfo(category: "Preamp", name: "Brit Plexi Brt Guitar Marshall Super Lead 100 (bright channel) (mono)"),
        "ccca": HelixModelInfo(category: "Preamp", name: "Brit Plexi Jump Guitar Marshall Super Lead 100 (jumped) (mono)"),
        "cccb": HelixModelInfo(category: "Preamp", name: "Brit Plexi Nrm Guitar Marshall Super Lead 100 (normal channel) (mono)"),
        "cccc": HelixModelInfo(category: "Preamp", name: "Cali Rectifire Guitar MESA/Boogie Dual Rectifier (mono)"),
        "cccd": HelixModelInfo(category: "Preamp", name: "Divided Duo Guitar 13 JRT 9/15 (mono)"),
        "ccce": HelixModelInfo(category: "Preamp", name: "Essex A15 Guitar Vox AC-15 (mono)"),
        "cccf": HelixModelInfo(category: "Preamp", name: "Essex A30 Guitar Vox AC-30 with top boost (mono)"),
        "ccd0": HelixModelInfo(category: "Preamp", name: "German Mahadeva Guitar Bogner Shiva (mono)"),
        "ccd1": HelixModelInfo(category: "Preamp", name: "German Ubersonic Guitar Bogner Ueberschall  (mono)"),
        "ccd2": HelixModelInfo(category: "Preamp", name: "Interstate Zed Guitar Dr Z Route 66 (mono)"),
        "ccd3": HelixModelInfo(category: "Preamp", name: "Jazz Rivet 120 Guitar Roland JC-120 Jazz Chorus (mono)"),
        "ccd4": HelixModelInfo(category: "Preamp", name: "Line 6 Doom Guitar Line 6 Original (mono)"),
        "ccd5": HelixModelInfo(category: "Preamp", name: "Line 6 Elektrik Guitar Line 6 Original (mono)"),
        "ccd6": HelixModelInfo(category: "Preamp", name: "Line 6 Epic Guitar Line 6 Original (mono)"),
        "ccd7": HelixModelInfo(category: "Preamp", name: "Mail Order Twin Guitar Silvertone 1484 (mono)"),
        "ccd8": HelixModelInfo(category: "Preamp", name: "Mandarin 80 Guitar Orange OR80 (mono)"),
        "ccd9": HelixModelInfo(category: "Preamp", name: "PV Panama Guitar Peavey 5150 (mono)"),
        "ccda": HelixModelInfo(category: "Preamp", name: "Solo Lead Clean Guitar Soldano SLO-100 (clean channel) (mono)"),
        "ccdb": HelixModelInfo(category: "Preamp", name: "Solo Lead Crunch Guitar Soldano SLO-100 (crunch channel) (mono)"),
        "ccdc": HelixModelInfo(category: "Preamp", name: "Solo Lead OD Guitar Soldano SLO-100 (overdrive channel) (mono)"),
        "ccdd": HelixModelInfo(category: "Preamp", name: "Soup Pro (mono)"),
        "ccde": HelixModelInfo(category: "Preamp", name: "Stone Age 185 (mono)"),
        "ccdf": HelixModelInfo(category: "Preamp", name: "Tweed Blues Brt (mono)"),
        "cce0": HelixModelInfo(category: "Preamp", name: "Tweed Blues Nrm (mono)"),
        "cce1": HelixModelInfo(category: "Preamp", name: "US Deluxe Nrm (mono)"),
        "cce2": HelixModelInfo(category: "Preamp", name: "US Deluxe Vib (mono)"),
        "cce3": HelixModelInfo(category: "Preamp", name: "US Double Nrm (mono)"),
        "cce4": HelixModelInfo(category: "Preamp", name: "US Double Vib (mono)"),
        "cce5": HelixModelInfo(category: "Preamp", name: "US Small Tweed (mono)"),
        "cce6": HelixModelInfo(category: "Preamp", name: "WhoWatt 100 (mono)"),
        "cce7": HelixModelInfo(category: "Amp", name: "Studio Tube Pre (mono)"),
        "cce8": HelixModelInfo(category: "Send/Return", name: "Send R (mono)"),
        "cce9": HelixModelInfo(category: "Send/Return", name: "Return L (mono)"),
        "ccec": HelixModelInfo(category: "Send/Return", name: "Send L/R (stereo)"),
        "ccee": HelixModelInfo(category: "Reverb", name: "63 Spring (legacy)"),
        "ccef": HelixModelInfo(category: "Reverb", name: "Cave (legacy)"),
        "ccf0": HelixModelInfo(category: "Reverb", name: "Chamber (legacy)"),
        "ccf1": HelixModelInfo(category: "Reverb", name: "Ducking (legacy)"),
        "ccf2": HelixModelInfo(category: "Reverb", name: "Echo (legacy)"),
        "ccf3": HelixModelInfo(category: "Reverb", name: "Hall (legacy)"),
        "ccf4": HelixModelInfo(category: "Reverb", name: "Octo (legacy)"),
        "ccf5": HelixModelInfo(category: "Reverb", name: "Particle Verb (legacy)"),
        "ccf6": HelixModelInfo(category: "Reverb", name: "Plate (legacy)"),
        "ccf7": HelixModelInfo(category: "Reverb", name: "Room (legacy)"),
        "ccf8": HelixModelInfo(category: "Reverb", name: "Spring (legacy)"),
        "ccf9": HelixModelInfo(category: "Reverb", name: "Tile (legacy)"),
        "ccfa": HelixModelInfo(category: "Send/Return", name: "Send/Return (mono)"),
        "ccfb": HelixModelInfo(category: "Send/Return", name: "Send L (mono)"),
        "ccfe": HelixModelInfo(category: "Send/Return", name: "FX Loop R (stereo)"),
        "001a3b": HelixModelInfo(category: "Amp+Cab", name: "Cali 400 Ch1  (mono)"),
        "011a3b": HelixModelInfo(category: "Amp+Cab", name: "Cali 400 Ch2  (mono)"),
        "021a49": HelixModelInfo(category: "Amp+Cab", name: "Cali Bass  (mono)"),
        "031a3c": HelixModelInfo(category: "Amp+Cab", name: "G Cougar 800  (mono)"),
        "041a4a": HelixModelInfo(category: "Amp+Cab", name: "Ampeg SVT Brt Bass Ampeg SVT (bright channel)  (mono)"),
        "051a4a": HelixModelInfo(category: "Amp+Cab", name: "Ampeg SVT Nrm Bass Ampeg SVT (normal channel)  (mono)"),
        "061a32": HelixModelInfo(category: "Amp+Cab", name: "Ampeg B-15NF Bass Ampeg B-15NF Portaflex  (mono)"),
        "071a35": HelixModelInfo(category: "Amp+Cab", name: "A30 Fawn Brt Guitar Vox AC-30 Fawn (bright channel)  (mono)"),
        "081a35": HelixModelInfo(category: "Amp+Cab", name: "A30 Fawn Nrm Guitar Vox AC-30 Fawn (normal channel)  (mono)"),
        "091a48": HelixModelInfo(category: "Amp+Cab", name: "ANGL Meteor Guitar ENGL Fireball 100  (mono)"),
        "0a1a3f": HelixModelInfo(category: "Amp+Cab", name: "Brit 2204 Guitar Marshall JCM-800  (mono)"),
        "0b1a41": HelixModelInfo(category: "Amp+Cab", name: "Brit J45 Brt Guitar Marshall JTM-45 (bright channel)  (mono)"),
        "0c1a41": HelixModelInfo(category: "Amp+Cab", name: "Brit J45 Nrm Guitar Marshall JTM-45 (normal channel)  (mono)"),
        "0d1a3f": HelixModelInfo(category: "Amp+Cab", name: "Brit P75 Brt Guitar Park 75 (bright channel)  (mono)"),
        "0e1a3f": HelixModelInfo(category: "Amp+Cab", name: "Brit P75 Nrm Guitar Park 75 (normal channel)  (mono)"),
        "0f1a42": HelixModelInfo(category: "Amp+Cab", name: "Brit Plexi Brt Guitar Marshall Super Lead 100 (bright channel)  (mono)"),
        "101a42": HelixModelInfo(category: "Amp+Cab", name: "Brit Plexi Jump Guitar Marshall Super Lead 100 (jumped)  (mono)"),
        "111a42": HelixModelInfo(category: "Amp+Cab", name: "Brit Plexi Nrm Guitar Marshall Super Lead 100 (normal channel)  (mono)"),
        "121a40": HelixModelInfo(category: "Amp+Cab", name: "Cali Rectifire Guitar MESA/Boogie Dual Rectifier  (mono)"),
        "131a2e": HelixModelInfo(category: "Amp+Cab", name: "Divided Duo Guitar 13 JRT 9/15  (mono)"),
        "141a2d": HelixModelInfo(category: "Amp+Cab", name: "Essex A15 Guitar Vox AC-15  (mono)"),
        "151a3a": HelixModelInfo(category: "Amp+Cab", name: "Essex A30 Guitar Vox AC-30 with top boost  (mono)"),
        "161a30": HelixModelInfo(category: "Amp+Cab", name: "German Mahadeva Guitar Bogner Shiva  (mono)"),
        "171a46": HelixModelInfo(category: "Amp+Cab", name: "German Ubersonic Guitar Bogner Ueberschall  (mono)"),
        "181a37": HelixModelInfo(category: "Amp+Cab", name: "Interstate Zed Guitar Dr Z Route 66  (mono)"),
        "191a38": HelixModelInfo(category: "Amp+Cab", name: "Jazz Rivet 120 Guitar Roland JC-120 Jazz Chorus  (mono)"),
        "1a1a47": HelixModelInfo(category: "Amp+Cab", name: "Line 6 Doom Guitar Line 6 Original  (mono)"),
        "1b1a3e": HelixModelInfo(category: "Amp+Cab", name: "Line 6 Elektrik Guitar Line 6 Original  (mono)"),
        "1c1a40": HelixModelInfo(category: "Amp+Cab", name: "Line 6 Epic Guitar Line 6 Original  (mono)"),
        "1d1a39": HelixModelInfo(category: "Amp+Cab", name: "Mail Order Twin Guitar Silvertone 1484  (mono)"),
        "1e1a43": HelixModelInfo(category: "Amp+Cab", name: "Mandarin 80 Guitar Orange OR80  (mono)"),
        "1f1a40": HelixModelInfo(category: "Amp+Cab", name: "PV Panama Guitar Peavey 5150  (mono)"),
        "201a44": HelixModelInfo(category: "Amp+Cab", name: "Solo Lead Clean Guitar Soldano SLO-100 (clean channel)  (mono)"),
        "211a44": HelixModelInfo(category: "Amp+Cab", name: "Solo Lead Crunch Guitar Soldano SLO-100 (crunch channel)  (mono)"),
        "221a44": HelixModelInfo(category: "Amp+Cab", name: "Solo Lead OD Guitar Soldano SLO-100 (overdrive channel)  (mono)"),
        "231a33": HelixModelInfo(category: "Amp+Cab", name: "Soup Pro  (mono)"),
        "241a2f": HelixModelInfo(category: "Amp+Cab", name: "Stone Age 185  (mono)"),
        "251a3d": HelixModelInfo(category: "Amp+Cab", name: "Tweed Blues Brt  (mono)"),
        "261a3d": HelixModelInfo(category: "Amp+Cab", name: "Tweed Blues Nrm  (mono)"),
        "271a31": HelixModelInfo(category: "Amp+Cab", name: "US Deluxe Nrm  (mono)"),
        "281a31": HelixModelInfo(category: "Amp+Cab", name: "US Deluxe Vib  (mono)"),
        "291a36": HelixModelInfo(category: "Amp+Cab", name: "US Double Nrm  (mono)"),
        "2a1a36": HelixModelInfo(category: "Amp+Cab", name: "US Double Vib  (mono)"),
        "2b1a34": HelixModelInfo(category: "Amp+Cab", name: "US Small Tweed  (mono)"),
        "2c1a47": HelixModelInfo(category: "Amp+Cab", name: "WhoWatt 100  (mono)"),
        "cd0104": HelixModelInfo(category: "Vol/Pan", name: "Gain (mono)"),
        "cd0105": HelixModelInfo(category: "Vol/Pan", name: "Volume Pedal  (mono)"),
        "cd0106": HelixModelInfo(category: "Vol/Pan", name: "Gain (stereo)"),
        "cd0107": HelixModelInfo(category: "Vol/Pan", name: "Pan (stereo)"),
        "cd0108": HelixModelInfo(category: "Vol/Pan", name: "Volume Pedal  (stereo)"),
        "cd0109": HelixModelInfo(category: "Wah", name: "Chrome Custom (mono)"),
        "cd010a": HelixModelInfo(category: "Wah", name: "Chrome (mono)"),
        "cd010b": HelixModelInfo(category: "Wah", name: "Colorful (mono)"),
        "cd010c": HelixModelInfo(category: "Wah", name: "Conductor (mono)"),
        "cd010d": HelixModelInfo(category: "Wah", name: "Fassel (mono)"),
        "cd010e": HelixModelInfo(category: "Wah", name: "Teardrop 310 (mono)"),
        "cd010f": HelixModelInfo(category: "Wah", name: "Throaty (mono)"),
        "cd0110": HelixModelInfo(category: "Wah", name: "UK Wah 846 (mono)"),
        "cd0111": HelixModelInfo(category: "Wah", name: "Vetta Wah (mono)"),
        "cd0112": HelixModelInfo(category: "Wah", name: "Weeper (mono)"),
        "cd0113": HelixModelInfo(category: "Wah", name: "Chrome Custom (stereo)"),
        "cd0114": HelixModelInfo(category: "Wah", name: "Chrome (stereo)"),
        "cd0115": HelixModelInfo(category: "Wah", name: "Colorful (stereo)"),
        "cd0116": HelixModelInfo(category: "Wah", name: "Conductor (stereo)"),
        "cd0117": HelixModelInfo(category: "Wah", name: "Fassel (stereo)"),
        "cd0118": HelixModelInfo(category: "Wah", name: "Teardrop 310 (stereo)"),
        "cd0119": HelixModelInfo(category: "Wah", name: "Throaty (stereo)"),
        "cd011a": HelixModelInfo(category: "Wah", name: "UK Wah 846 (stereo)"),
        "cd011b": HelixModelInfo(category: "Wah", name: "Vetta Wah (stereo)"),
        "cd011c": HelixModelInfo(category: "Wah", name: "Weeper (stereo)"),
        "cd011d": HelixModelInfo(category: "Delay", name: "Reverse Delay Mono, Stereo Line 6 Original (mono)"),
        "cd011e": HelixModelInfo(category: "Delay", name: "Reverse Delay Mono, Stereo Line 6 Original (stereo)"),
        "cd011f": HelixModelInfo(category: "Delay", name: "Dual Delay  (stereo)"),
        "cd0120": HelixModelInfo(category: "Distortion", name: "KWB Mono, Stereo Benadrian Kowloon Walled Bunny Distortion (mono)"),
        "cd0121": HelixModelInfo(category: "Distortion", name: "KWB Mono, Stereo Benadrian Kowloon Walled Bunny Distortion (stereo)"),
        "cd0122": HelixModelInfo(category: "Distortion", name: "Bitcrusher Mono, Stereo Line 6 Original (mono)"),
        "cd0123": HelixModelInfo(category: "Distortion", name: "Bitcrusher Mono, Stereo Line 6 Original (stereo)"),
        "cd0124": HelixModelInfo(category: "Modulation", name: "Tremolo/Autopan (mono)"),
        "cd0125": HelixModelInfo(category: "Modulation", name: "Tremolo/Autopan (stereo)"),
        "cd0126": HelixModelInfo(category: "Modulation", name: "Deluxe Phaser (mono)"),
        "cd0127": HelixModelInfo(category: "Modulation", name: "Deluxe Phaser (stereo)"),
        "cd0128": HelixModelInfo(category: "Pitch/Synth", name: "Simple Pitch (mono)"),
        "cd0129": HelixModelInfo(category: "Pitch/Synth", name: "Simple Pitch (stereo)"),
        "cd012a": HelixModelInfo(category: "Pitch/Synth", name: "Dual Pitch (mono)"),
        "cd012b": HelixModelInfo(category: "Pitch/Synth", name: "Dual Pitch (stereo)"),
        "cd012c": HelixModelInfo(category: "Filter", name: "Autofilter (mono)"),
        "cd012d": HelixModelInfo(category: "Filter", name: "Autofilter (stereo)"),
        "cd012e": HelixModelInfo(category: "Distortion", name: "Teemah! (mono)"),
        "cd012f": HelixModelInfo(category: "Distortion", name: "Teemah! (stereo)"),
        "cd0130": HelixModelInfo(category: "Modulation", name: "Dynamix Flanger (mono)"),
        "cd0131": HelixModelInfo(category: "Modulation", name: "Dynamix Flanger (stereo)"),
        "cd0132": HelixModelInfo(category: "Amp", name: "Matchstick Ch1 Guitar Matchless DC30 (channel 1) (mono)"),
        "cd0133": HelixModelInfo(category: "Amp", name: "Matchstick Ch2 Guitar Matchless DC30 (channel 2) (mono)"),
        "cd0134": HelixModelInfo(category: "Amp", name: "Matchstick Jump Guitar Matchless DC30 (jumped) (mono)"),
        "cd0135": HelixModelInfo(category: "Preamp", name: "Matchstick Ch1 Guitar Matchless DC30 (channel 1) (mono)"),
        "cd0136": HelixModelInfo(category: "Preamp", name: "Matchstick Ch2 Guitar Matchless DC30 (channel 2) (mono)"),
        "cd0137": HelixModelInfo(category: "Preamp", name: "Matchstick Jump Guitar Matchless DC30 (jumped) (mono)"),
        "cd0138": HelixModelInfo(category: "Amp", name: "Cali IV Lead Guitar MESA/Boogie Mark IV (lead channel) (mono)"),
        "cd0139": HelixModelInfo(category: "Amp", name: "Cali IV Rhythm 1 Guitar MESA/Boogie Mark IV (channel I) (mono)"),
        "cd013a": HelixModelInfo(category: "Amp", name: "Cali IV Rhythm 2 Guitar MESA/Boogie Mark IV (channel II) (mono)"),
        "cd013b": HelixModelInfo(category: "Preamp", name: "Cali IV Lead Guitar MESA/Boogie Mark IV (lead channel) (mono)"),
        "cd013c": HelixModelInfo(category: "Preamp", name: "Cali IV Rhythm 1 Guitar MESA/Boogie Mark IV (channel I) (mono)"),
        "cd013d": HelixModelInfo(category: "Preamp", name: "Cali IV Rhythm 2 Guitar MESA/Boogie Mark IV (channel II) (mono)"),
        "cd013e": HelixModelInfo(category: "Modulation", name: "Harmonic Tremolo (mono)"),
        "cd013f": HelixModelInfo(category: "Modulation", name: "Harmonic Tremolo (stereo)"),
        "cd0140": HelixModelInfo(category: "Distortion", name: "Wringer Fuzz Mono, Stereo Garbages modded BOSS FZ-2 (mono)"),
        "cd0141": HelixModelInfo(category: "Distortion", name: "Wringer Fuzz Mono, Stereo Garbages modded BOSS FZ-2 (stereo)"),
        "cd0142": HelixModelInfo(category: "Amp", name: "Line 6 2204 Mod Guitar Line 6 Original (mono)"),
        "cd0143": HelixModelInfo(category: "EQ", name: "Cali Q Graphic (mono)"),
        "cd0144": HelixModelInfo(category: "EQ", name: "Cali Q Graphic (stereo)"),
        "cd0148": HelixModelInfo(category: "Amp", name: "Line 6 Fatality Guitar Line 6 Original (mono)"),
        "cd0149": HelixModelInfo(category: "Preamp", name: "Line 6 Fatality Guitar Line 6 Original (mono)"),
        "cd014a": HelixModelInfo(category: "Preamp", name: "Line 6 2204 Mod Guitar Line 6 Original (mono)"),
        "cd014b": HelixModelInfo(category: "Delay", name: "Vintage Digital Mono, Stereo Line 6 Original (mono)"),
        "cd014c": HelixModelInfo(category: "Delay", name: "Vintage Digital Mono, Stereo Line 6 Original (stereo)"),
        "cd014d": HelixModelInfo(category: "Delay", name: "Pitch Echo Mono, Stereo Line 6 Original (mono)"),
        "cd014e": HelixModelInfo(category: "Delay", name: "Pitch Echo Mono, Stereo Line 6 Original (stereo)"),
        "cd014f": HelixModelInfo(category: "Amp", name: "Archetype Clean Guitar Paul Reed Smith Archon (clean channel) (mono)"),
        "cd0150": HelixModelInfo(category: "Amp", name: "Archetype Lead Guitar Paul Reed Smith Archon (lead channel) (mono)"),
        "cd0151": HelixModelInfo(category: "Preamp", name: "Archetype Clean Guitar Paul Reed Smith Archon (clean channel) (mono)"),
        "cd0152": HelixModelInfo(category: "Preamp", name: "Archetype Lead Guitar Paul Reed Smith Archon (lead channel) (mono)"),
        "cd0153": HelixModelInfo(category: "Amp", name: "Line 6 Litigator Guitar Line 6 Original (mono)"),
        "cd0154": HelixModelInfo(category: "Distortion", name: "Stupor OD (mono)"),
        "cd0155": HelixModelInfo(category: "Distortion", name: "Stupor OD (stereo)"),
        "cd0156": HelixModelInfo(category: "Preamp", name: "Line 6 Litigator Guitar Line 6 Original (mono)"),
        "cd0157": HelixModelInfo(category: "Amp", name: "Del Sol 300 (mono)"),
        "cd0158": HelixModelInfo(category: "Preamp", name: "Del Sol 300 (mono)"),
        "cd0159": HelixModelInfo(category: "Delay", name: "Adriatic Swell Mono, Stereo Line 6 Original (mono)"),
        "cd015a": HelixModelInfo(category: "Delay", name: "Adriatic Swell Mono, Stereo Line 6 Original (stereo)"),
        "cd015b": HelixModelInfo(category: "Delay", name: "Vintage Swell Mono, Stereo Line 6 Original (mono)"),
        "cd015c": HelixModelInfo(category: "Delay", name: "Vintage Swell Mono, Stereo Line 6 Original (stereo)"),
        "cd015d": HelixModelInfo(category: "Amp", name: "Line 6 Badonk Guitar Line 6 Original (mono)"),
        "cd015e": HelixModelInfo(category: "Amp", name: "Woody Blue (mono)"),
        "cd015f": HelixModelInfo(category: "Distortion", name: "Obsidian 7000 Mono, Stereo Darkglass Electronics Microtubes B7K Ultra (mono)"),
        "cd0160": HelixModelInfo(category: "Distortion", name: "Obsidian 7000 Mono, Stereo Darkglass Electronics Microtubes B7K Ultra (stereo)"),
        "cd0161": HelixModelInfo(category: "Preamp", name: "Woody Blue (mono)"),
        "cd0162": HelixModelInfo(category: "Preamp", name: "Line 6 Badonk Guitar Line 6 Original (mono)"),
        "cd0163": HelixModelInfo(category: "Cab", name: "1x12 Cali Ext Single, Dual 1x12\" MESA/Boogie EVM12L (mono)"),
        "cd0164": HelixModelInfo(category: "Cab", name: "1x12 Cali IV Single, Dual 1x12\" MESA/Boogie Mk IV (mono)"),
        "cd0165": HelixModelInfo(category: "Cab", name: "1x12 Del Sol (mono)"),
        "cd0166": HelixModelInfo(category: "Cab", name: "2x12 Match G25 Single, Dual 1x12\" Matchless DC-30 Greenback 25 (mono)"),
        "cd0167": HelixModelInfo(category: "Cab", name: "2x12 Match H30 Single, Dual 1x12\" Matchless DC-30 G12H30 (mono)"),
        "cd0168": HelixModelInfo(category: "Cab", name: "1x18 Del Sol (mono)"),
        "cd0169": HelixModelInfo(category: "Dynamic", name: "Autoswell (mono)"),
        "cd016a": HelixModelInfo(category: "Dynamic", name: "Autoswell (stereo)"),
        "cd016b": HelixModelInfo(category: "Amp", name: "Busy One Ch1 (mono)"),
        "cd016c": HelixModelInfo(category: "Amp", name: "Busy One Ch2 (mono)"),
        "cd016d": HelixModelInfo(category: "Amp", name: "Busy One Jump (mono)"),
        "cd016e": HelixModelInfo(category: "Cab", name: "1x18 Woody Blue  (mono)"),
        "cd016f": HelixModelInfo(category: "Dynamic", name: "3-Band Comp (mono)"),
        "cd0170": HelixModelInfo(category: "Dynamic", name: "3-Band Comp (stereo)"),
        "cd0172": HelixModelInfo(category: "Preamp", name: "Busy One Ch1 (mono)"),
        "cd0173": HelixModelInfo(category: "Preamp", name: "Busy One Ch2 (mono)"),
        "cd0174": HelixModelInfo(category: "Preamp", name: "Busy One Jump (mono)"),
        "cd0175": HelixModelInfo(category: "Pitch/Synth", name: "4 OSC Generator (stereo)"),
        "cd0177": HelixModelInfo(category: "Modulation", name: "PlastiChorus (mono)"),
        "cd0178": HelixModelInfo(category: "Modulation", name: "PlastiChorus (stereo)"),
        "cd0179": HelixModelInfo(category: "Pitch/Synth", name: "3 Note Generator (mono)"),
        "cd017a": HelixModelInfo(category: "Pitch/Synth", name: "3 Note Generator (stereo)"),
        "cd017b": HelixModelInfo(category: "Pitch/Synth", name: "4 OSC Generator (mono)"),
        "cd0180": HelixModelInfo(category: "Amp", name: "Derailed Ingrid Guitar Trainwreck Circuits Express (mono)"),
        "cd0181": HelixModelInfo(category: "Preamp", name: "Derailed Ingrid Guitar Trainwreck Circuits Express (mono)"),
        "cd0182": HelixModelInfo(category: "Distortion", name: "Thrifter Fuzz Mono, Stereo Line 6 Original (mono)"),
        "cd0183": HelixModelInfo(category: "Distortion", name: "Thrifter Fuzz Mono, Stereo Line 6 Original (stereo)"),
        "cd0184": HelixModelInfo(category: "Distortion", name: "Kinky Boost (mono)"),
        "cd0185": HelixModelInfo(category: "Distortion", name: "Kinky Boost (stereo)"),
        "cd0186": HelixModelInfo(category: "Modulation", name: "Bleat Chop Trem (mono)"),
        "cd0187": HelixModelInfo(category: "Modulation", name: "Bleat Chop Trem (stereo)"),
        "cd0188": HelixModelInfo(category: "Modulation", name: "Double Take Mono, Stereo Line 6 Original (mono)"),
        "cd0189": HelixModelInfo(category: "Modulation", name: "Double Take Mono, Stereo Line 6 Original (stereo)"),
        "cd018a": HelixModelInfo(category: "Delay", name: "Cosmos Echo Mono, Stereo Roland RE-201 Space Echo (mono)"),
        "cd018b": HelixModelInfo(category: "Delay", name: "Cosmos Echo Mono, Stereo Roland RE-201 Space Echo (stereo)"),
        "cd018c": HelixModelInfo(category: "Vol/Pan", name: "Stereo Width (stereo)"),
        "cd018d": HelixModelInfo(category: "Amp", name: "Voltage Queen (mono)"),
        "cd018e": HelixModelInfo(category: "Preamp", name: "Voltage Queen (mono)"),
        "cd018f": HelixModelInfo(category: "Delay", name: "Analog Echo (legacy)"),
        "cd0190": HelixModelInfo(category: "Delay", name: "Analog w/Mod (legacy)"),
        "cd0191": HelixModelInfo(category: "Delay", name: "Auto-Volume Echo (legacy)"),
        "cd0192": HelixModelInfo(category: "Delay", name: "Digital Legacy Line 6 Original (legacy)"),
        "cd0193": HelixModelInfo(category: "Delay", name: "Dig w/Mod Legacy Line 6 Original (legacy)"),
        "cd0194": HelixModelInfo(category: "Delay", name: "Dynamic Legacy TC Electronic 2290 (legacy)"),
        "cd0195": HelixModelInfo(category: "Delay", name: "Echo Platter (legacy)"),
        "cd0196": HelixModelInfo(category: "Delay", name: "Lo Res Legacy Line 6 Original (legacy)"),
        "cd0197": HelixModelInfo(category: "Delay", name: "Multi-Head (legacy)"),
        "cd0198": HelixModelInfo(category: "Delay", name: "Ping Pong Legacy Line 6 Original (legacy)"),
        "cd0199": HelixModelInfo(category: "Delay", name: "Reverse Legacy Line 6 Original (legacy)"),
        "cd019a": HelixModelInfo(category: "Delay", name: "Stereo Legacy Line 6 Original (legacy)"),
        "cd019b": HelixModelInfo(category: "Delay", name: "Sweep Echo (legacy)"),
        "cd019c": HelixModelInfo(category: "Delay", name: "Tape Echo (legacy)"),
        "cd019d": HelixModelInfo(category: "Delay", name: "Tube Echo (legacy)"),
        "cd019e": HelixModelInfo(category: "Pitch/Synth", name: "Bass Octaver (legacy)"),
        "cd01a2": HelixModelInfo(category: "Distortion", name: "Buzz Saw Legacy Maestro Fuzz Tone (legacy)"),
        "cd01a3": HelixModelInfo(category: "Distortion", name: "Classic Dist Legacy ProCo RAT (legacy)"),
        "cd01a4": HelixModelInfo(category: "Distortion", name: "Colordrive Legacy Colorsound Overdriver (legacy)"),
        "cd01a5": HelixModelInfo(category: "Distortion", name: "Facial Fuzz Legacy Arbiter Fuzz Face (legacy)"),
        "cd01a6": HelixModelInfo(category: "Distortion", name: "Fuzz Pi (legacy)"),
        "cd01a7": HelixModelInfo(category: "Distortion", name: "Heavy Dist Legacy BOSS Metal Zone (legacy)"),
        "cd01a8": HelixModelInfo(category: "Distortion", name: "Jet Fuzz (legacy)"),
        "cd01a9": HelixModelInfo(category: "Distortion", name: "Jumbo Fuzz Legacy Vox Tone Bender (legacy)"),
        "cd01aa": HelixModelInfo(category: "Distortion", name: "L6 Distortion (legacy)"),
        "cd01ab": HelixModelInfo(category: "Distortion", name: "L6 Drive (legacy)"),
        "cd01ac": HelixModelInfo(category: "Distortion", name: "Octave Fuzz (legacy)"),
        "cd01ad": HelixModelInfo(category: "Distortion", name: "Overdrive Legacy DOD Overdrive/Preamp 250 (legacy)"),
        "cd01af": HelixModelInfo(category: "Distortion", name: "Screamer Legacy Ibanez Tube Screamer (legacy)"),
        "cd01b0": HelixModelInfo(category: "Distortion", name: "Sub Oct Fuzz (legacy)"),
        "cd01b2": HelixModelInfo(category: "Distortion", name: "Tube Drive Legacy Chandler Tube Driver (legacy)"),
        "cd01b5": HelixModelInfo(category: "Pitch/Synth", name: "Attack Synth (legacy)"),
        "cd01b6": HelixModelInfo(category: "Filter", name: "Comet Trails (legacy)"),
        "cd01b7": HelixModelInfo(category: "Pitch/Synth", name: "Growler (legacy)"),
        "cd01b8": HelixModelInfo(category: "Filter", name: "Obi Wah (legacy)"),
        "cd01b9": HelixModelInfo(category: "Pitch/Synth", name: "Octi Synth (legacy)"),
        "cd01ba": HelixModelInfo(category: "Filter", name: "Q Filter (legacy)"),
        "cd01bb": HelixModelInfo(category: "Filter", name: "Seeker (legacy)"),
        "cd01bc": HelixModelInfo(category: "Filter", name: "Slow Filter (legacy)"),
        "cd01bd": HelixModelInfo(category: "Filter", name: "Spin Cycle (legacy)"),
        "cd01be": HelixModelInfo(category: "Pitch/Synth", name: "Synth O Matic (legacy)"),
        "cd01bf": HelixModelInfo(category: "Pitch/Synth", name: "Synth String (legacy)"),
        "cd01c0": HelixModelInfo(category: "Filter", name: "Throbber (legacy)"),
        "cd01c1": HelixModelInfo(category: "Filter", name: "Tron Down (legacy)"),
        "cd01c2": HelixModelInfo(category: "Filter", name: "Tron Up (legacy)"),
        "cd01c3": HelixModelInfo(category: "Filter", name: "Voice Box (legacy)"),
        "cd01c4": HelixModelInfo(category: "Filter", name: "V Tron (legacy)"),
        "cd01c5": HelixModelInfo(category: "Modulation", name: "Frequency Shift Legacy Line 6 Original  (legacy)"),
        "cd01c6": HelixModelInfo(category: "Modulation", name: "80A Flanger Legacy A/DA Flanger  (legacy)"),
        "cd01c7": HelixModelInfo(category: "Modulation", name: "Tri Chorus Legacy Dytronics Tri-Stereo Chorus  (legacy)"),
        "cd01c8": HelixModelInfo(category: "Modulation", name: "Jet Flanger Legacy A/DA Flanger  (legacy)"),
        "cd01c9": HelixModelInfo(category: "Modulation", name: "Dual Phaser Legacy Mu-Tron Bi-Phase  (legacy)"),
        "cd01ca": HelixModelInfo(category: "Modulation", name: "Bias Tremolo Legacy 1960 Vox AC-15 Tremolo  (legacy)"),
        "cd01cb": HelixModelInfo(category: "Modulation", name: "Analog Chorus Legacy BOSS CE-1  (legacy)"),
        "cd01cc": HelixModelInfo(category: "Modulation", name: "U-Vibe Legacy Shin-ei Uni-Vibe  (legacy)"),
        "cd01cd": HelixModelInfo(category: "Modulation", name: "Ring Modulator Legacy Line 6 Original  (legacy)"),
        "cd01ce": HelixModelInfo(category: "Modulation", name: "AC Flanger Legacy MXR Flanger  (legacy)"),
        "cd01cf": HelixModelInfo(category: "Modulation", name: "Opto Tremolo Legacy 1964 Fender Deluxe Reverb  (legacy)"),
        "cd01d0": HelixModelInfo(category: "Modulation", name: "Barberpole Legacy Line 6 Original  (legacy)"),
        "cd01d1": HelixModelInfo(category: "Modulation", name: "Panner Legacy Line 6 Original  (legacy)"),
        "cd01d2": HelixModelInfo(category: "Modulation", name: "Pattern Tremolo Legacy Line 6 Original  (legacy)"),
        "cd01d3": HelixModelInfo(category: "Modulation", name: "Pitch Vibrato Legacy BOSS VB-2  (legacy)"),
        "cd01d4": HelixModelInfo(category: "Modulation", name: "Dimension Legacy Roland Dimension D  (legacy)"),
        "cd01d5": HelixModelInfo(category: "Modulation", name: "Rotary Drum Legacy Fender Vibratone  (legacy)"),
        "cd01d6": HelixModelInfo(category: "Modulation", name: "Rotary Drum/Horn  (legacy)"),
        "cd01d8": HelixModelInfo(category: "Modulation", name: "Panned Phaser Legacy Ibanez Flying Pan  (legacy)"),
        "cd01d9": HelixModelInfo(category: "Modulation", name: "Analog Flanger Legacy MXR Flanger  (legacy)"),
        "cd01da": HelixModelInfo(category: "Modulation", name: "Phaser Legacy MXR Phase 90  (legacy)"),
        "cd01db": HelixModelInfo(category: "Pitch/Synth", name: "Smart Harmony (legacy)"),
        "cd01dc": HelixModelInfo(category: "Dynamic", name: "Kinky Comp (mono)"),
        "cd01dd": HelixModelInfo(category: "Dynamic", name: "Kinky Comp (stereo)"),
        "cd01de": HelixModelInfo(category: "Amp", name: "Brit Trem Nrm Guitar Marshall JTM-50 (normal channel) (mono)"),
        "cd01df": HelixModelInfo(category: "Amp", name: "Brit Trem Brt Guitar Marshall JTM-50 (bright channel) (mono)"),
        "cd01e0": HelixModelInfo(category: "Amp", name: "Brit Trem Jump Guitar Marshall JTM-50 (jumped) (mono)"),
        "cd01e1": HelixModelInfo(category: "Preamp", name: "Brit Trem Nrm Guitar Marshall JTM-50 (normal channel) (mono)"),
        "cd01e2": HelixModelInfo(category: "Preamp", name: "Brit Trem Brt Guitar Marshall JTM-50 (bright channel) (mono)"),
        "cd01e3": HelixModelInfo(category: "Preamp", name: "Brit Trem Jump Guitar Marshall JTM-50 (jumped) (mono)"),
        "cd01e4": HelixModelInfo(category: "Amp", name: "Cartographer Guitar Ben Adrian Cartographer (mono)"),
        "cd01e5": HelixModelInfo(category: "Preamp", name: "Cartographer Guitar Ben Adrian Cartographer (mono)"),
        "cd01e6": HelixModelInfo(category: "Amp", name: "Agua 51 (mono)"),
        "cd01e7": HelixModelInfo(category: "Preamp", name: "Agua 51 (mono)"),
        "cd01e8": HelixModelInfo(category: "Delay", name: "Multi Pass Mono, Stereo Line 6 Original (mono)"),
        "cd01e9": HelixModelInfo(category: "Delay", name: "Multi Pass Mono, Stereo Line 6 Original (stereo)"),
        "cd01ea": HelixModelInfo(category: "Reverb", name: "Glitz (mono)"),
        "cd01eb": HelixModelInfo(category: "Reverb", name: "Glitz (stereo)"),
        "cd01ec": HelixModelInfo(category: "Reverb", name: "Ganymede (stereo)"),
        "cd01ed": HelixModelInfo(category: "Reverb", name: "Searchlights (stereo)"),
        "cd01ee": HelixModelInfo(category: "Reverb", name: "Double Tank (mono)"),
        "cd01ef": HelixModelInfo(category: "Reverb", name: "Double Tank (stereo)"),
        "cd01f0": HelixModelInfo(category: "Reverb", name: "Ganymede (mono)"),
        "cd01f1": HelixModelInfo(category: "Reverb", name: "Plateaux (mono)"),
        "cd01f2": HelixModelInfo(category: "Reverb", name: "Plateaux (stereo)"),
        "cd01f3": HelixModelInfo(category: "Reverb", name: "Searchlights (mono)"),
        "cd01f4": HelixModelInfo(category: "Amp", name: "Placater Dirty Guitar Friedman BE-100 (BE/HBE channel) (mono)"),
        "cd01f5": HelixModelInfo(category: "Preamp", name: "Placater Dirty Guitar Friedman BE-100 (BE/HBE channel) (mono)"),
        "cd01f6": HelixModelInfo(category: "Amp", name: "Cali Texas Ch2 Guitar MESA/Boogie Lone Star (drive channel) (mono)"),
        "cd01f7": HelixModelInfo(category: "Preamp", name: "Cali Texas Ch2 Guitar MESA/Boogie Lone Star (drive channel) (mono)"),
        "cd01fa": HelixModelInfo(category: "Distortion", name: "Deez One Mod (mono)"),
        "cd01fb": HelixModelInfo(category: "Distortion", name: "Deez One Mod (stereo)"),
        "cd01fc": HelixModelInfo(category: "Distortion", name: "Deez One Vintage (mono)"),
        "cd01fd": HelixModelInfo(category: "Distortion", name: "Deez One Vintage (stereo)"),
        "cd01fe": HelixModelInfo(category: "Distortion", name: "Deranged Master (mono)"),
        "cd01ff": HelixModelInfo(category: "Distortion", name: "Deranged Master (stereo)"),
        "cd0200": HelixModelInfo(category: "Amp", name: "Placater Clean Guitar Friedman BE-100 (clean channel) (mono)"),
        "cd0201": HelixModelInfo(category: "Preamp", name: "Placater Clean Guitar Friedman BE-100 (clean channel) (mono)"),
        "cd0202": HelixModelInfo(category: "Amp", name: "Cali Texas Ch1 Guitar MESA/Boogie Lone Star (clean channel) (mono)"),
        "cd0203": HelixModelInfo(category: "Preamp", name: "Cali Texas Ch1 Guitar MESA/Boogie Lone Star (clean channel) (mono)"),
        "cd0207": HelixModelInfo(category: "Amp", name: "Ampeg SVT-4 PRO (mono)"),
        "cd0208": HelixModelInfo(category: "Preamp", name: "Ampeg SVT-4 PRO (mono)"),
        "cd0209": HelixModelInfo(category: "Distortion", name: "Ampeg Scrambler Mono, Stereo Ampeg Scrambler Bass Overdrive (mono)"),
        "cd020a": HelixModelInfo(category: "Distortion", name: "Ampeg Scrambler Mono, Stereo Ampeg Scrambler Bass Overdrive (stereo)"),
        "cd020b": HelixModelInfo(category: "Distortion", name: "ZeroAmp Bass DI Mono, Stereo Tech 21 SansAmp Bass Driver DI V1 (mono)"),
        "cd020c": HelixModelInfo(category: "Distortion", name: "ZeroAmp Bass DI Mono, Stereo Tech 21 SansAmp Bass Driver DI V1 (stereo)"),
        "cd020d": HelixModelInfo(category: "Distortion", name: "Dhyana Drive (mono)"),
        "cd020e": HelixModelInfo(category: "Distortion", name: "Dhyana Drive (stereo)"),
        "cd020f": HelixModelInfo(category: "EQ", name: "Low/High Shelf (mono)"),
        "cd0210": HelixModelInfo(category: "EQ", name: "Low/High Shelf (stereo)"),
        "cd0211": HelixModelInfo(category: "EQ", name: "Tilt (mono)"),
        "cd0212": HelixModelInfo(category: "EQ", name: "Tilt (stereo)"),
        "cd0213": HelixModelInfo(category: "Filter", name: "Asheville Pattrn (mono)"),
        "cd0214": HelixModelInfo(category: "Filter", name: "Asheville Pattrn (stereo)"),
        "cd0215": HelixModelInfo(category: "Amp", name: "GrammaticoLG Brt (mono)"),
        "cd0216": HelixModelInfo(category: "Amp", name: "GrammaticoLG Jmp (mono)"),
        "cd0217": HelixModelInfo(category: "Amp", name: "GrammaticoLG Nrm (mono)"),
        "cd0218": HelixModelInfo(category: "Preamp", name: "GrammaticoLG Brt (mono)"),
        "cd0219": HelixModelInfo(category: "Preamp", name: "GrammaticoLG Jmp (mono)"),
        "cd021a": HelixModelInfo(category: "Preamp", name: "GrammaticoLG Nrm (mono)"),
        "cd021b": HelixModelInfo(category: "Amp", name: "Fullerton Brt (mono)"),
        "cd021c": HelixModelInfo(category: "Amp", name: "Fullerton Jump (mono)"),
        "cd021d": HelixModelInfo(category: "Amp", name: "Fullerton Nrm (mono)"),
        "cd021e": HelixModelInfo(category: "Preamp", name: "Fullerton Brt (mono)"),
        "cd021f": HelixModelInfo(category: "Preamp", name: "Fullerton Jump (mono)"),
        "cd0220": HelixModelInfo(category: "Preamp", name: "Fullerton Nrm (mono)"),
        "cd0221": HelixModelInfo(category: "Amp", name: "Revv Gen Red Guitar Revv Generator 120 (red/high gain ch. 4) (mono)"),
        "cd0222": HelixModelInfo(category: "Preamp", name: "Revv Gen Red Guitar Revv Generator 120 (red/high gain ch. 4) (mono)"),
        "cd0223": HelixModelInfo(category: "Distortion", name: "Heir Apparent (mono)"),
        "cd0224": HelixModelInfo(category: "Distortion", name: "Heir Apparent (stereo)"),
        "cd0225": HelixModelInfo(category: "Distortion", name: "Tone Sovereign (mono)"),
        "cd0226": HelixModelInfo(category: "Distortion", name: "Tone Sovereign (stereo)"),
        "cd0227": HelixModelInfo(category: "Cab", name: "1x12 Fullerton Single, Dual 1x12\" Fender 5C3 Tweed Deluxe (mono)"),
        "cd0228": HelixModelInfo(category: "Cab", name: "1x12 Grammatico Single, Dual 1x12\" Grammatico LaGrange (mono)"),
        "cd0229": HelixModelInfo(category: "Distortion", name: "Alpaca Rogue (mono)"),
        "cd022a": HelixModelInfo(category: "Distortion", name: "Alpaca Rogue (stereo)"),
        "cd022b": HelixModelInfo(category: "Distortion", name: "Xenomorph Fuzz Mono, Stereo Subdecay Harmonic Antagonizer (mono)"),
        "cd022c": HelixModelInfo(category: "Distortion", name: "Xenomorph Fuzz Mono, Stereo Subdecay Harmonic Antagonizer (stereo)"),
        "cd022d": HelixModelInfo(category: "Dynamic", name: "Rochester Comp (mono)"),
        "cd022e": HelixModelInfo(category: "Dynamic", name: "Rochester Comp (stereo)"),
        "cd022f": HelixModelInfo(category: "Modulation", name: "Pebble Phaser (mono)"),
        "cd0230": HelixModelInfo(category: "Modulation", name: "Pebble Phaser (stereo)"),
        "cd0231": HelixModelInfo(category: "Amp", name: "Revv Gen Purple Guitar Revv Generator 120 (purple/gain ch. 3) (mono)"),
        "cd0232": HelixModelInfo(category: "Preamp", name: "Revv Gen Purple Guitar Revv Generator 120 (purple/gain ch. 3) (mono)"),
        "cd0234": HelixModelInfo(category: "Distortion", name: "Legendary Drive Mono, Stereo Carvin VLD1 Legacy Drive (hi gain channel) (mono)"),
        "cd0235": HelixModelInfo(category: "Distortion", name: "Legendary Drive Mono, Stereo Carvin VLD1 Legacy Drive (hi gain channel) (stereo)"),
        "cd0236": HelixModelInfo(category: "Distortion", name: "Bighorn Fuzz Mono, Stereo 73 Electro-Harmonix RamGerman Ubersonic Guitar Bogner Ueberschall  (mono)s Head Big Muff Pi (mono)"),
        "cd0237": HelixModelInfo(category: "Distortion", name: "Bighorn Fuzz Mono, Stereo 73 Electro-Harmonix Rams Head Big Muff Pi (stereo)"),
        "cd0238": HelixModelInfo(category: "Delay", name: "Glitch Delay Mono, Stereo Line 6 Original (mono)"),
        "cd0239": HelixModelInfo(category: "Delay", name: "Glitch Delay Mono, Stereo Line 6 Original (stereo)"),
        "cd023d": HelixModelInfo(category: "Pitch/Synth", name: "Poly Pitch (mono)"),
        "cd023e": HelixModelInfo(category: "Pitch/Synth", name: "Poly Capo (mono)"),
        "cd023f": HelixModelInfo(category: "Pitch/Synth", name: "Poly Wham (mono)"),
        "cd0240": HelixModelInfo(category: "Modulation", name: "Poly Detune Mono Line 6 Original (mono)"),
        "cd0242": HelixModelInfo(category: "Pitch/Synth", name: "12 String (mono)"),
        "cd0243": HelixModelInfo(category: "Delay", name: "Poly Sustain Mono Line 6 Original (mono)"),
        "cd0244": HelixModelInfo(category: "EQ", name: "Acoustic Sim (mono)"),
        "cd0245": HelixModelInfo(category: "EQ", name: "Acoustic Sim (stereo)"),
        "cd0246": HelixModelInfo(category: "Distortion", name: "Horizon Drive (mono)"),
        "cd0247": HelixModelInfo(category: "Distortion", name: "Horizon Drive (stereo)"),
        "cd0248": HelixModelInfo(category: "Distortion", name: "Swedish Chainsaw Mono, Stereo Boss HM-2 Heavy Metal Distortion (MIJ) (mono)"),
        "cd0249": HelixModelInfo(category: "Distortion", name: "Swedish Chainsaw Mono, Stereo Boss HM-2 Heavy Metal Distortion (MIJ) (stereo)"),
        "cd024c": HelixModelInfo(category: "Vol/Pan", name: "Stereo Imager (stereo)"),
        "cd024d": HelixModelInfo(category: "Cab", name: "1x10 US Princess Single, Dual 1x10\" Fender Princeton Reverb (mono)"),
        "cd024e": HelixModelInfo(category: "Cab", name: "1x12 US Princess Single, Dual 1x12\" Fender Princeton Reverb (mono)"),
        "cd024f": HelixModelInfo(category: "Amp", name: "US Princess (mono)"),
        "cd0250": HelixModelInfo(category: "Preamp", name: "US Princess (mono)"),
        "cd0251": HelixModelInfo(category: "Distortion", name: "Ballistic Fuzz Mono, Stereo Euthymia ICBM Fuzz (mono)"),
        "cd0252": HelixModelInfo(category: "Distortion", name: "Ballistic Fuzz Mono, Stereo Euthymia ICBM Fuzz (stereo)"),
        "cd0253": HelixModelInfo(category: "Distortion", name: "Pocket Fuzz Mono, Stereo Jordan Boss Tone Fuzz (mono)"),
        "cd0254": HelixModelInfo(category: "Distortion", name: "Pocket Fuzz Mono, Stereo Jordan Boss Tone Fuzz (stereo)"),
        "cd0255": HelixModelInfo(category: "Dynamic", name: "Horizon Gate (mono)"),
        "cd0256": HelixModelInfo(category: "Dynamic", name: "Horizon Gate (stereo)"),
        "cd0257": HelixModelInfo(category: "Amp", name: "Das Benzin Lead Guitar Diezel VH4 (lead chanel) (mono)"),
        "cd0258": HelixModelInfo(category: "Preamp", name: "Das Benzin Lead Guitar Diezel VH4 (lead chanel) (mono)"),
        "cd0259": HelixModelInfo(category: "Amp", name: "Das Benzin Mega Guitar Diezel VH4 (mega chanel) (mono)"),
        "cd025a": HelixModelInfo(category: "Preamp", name: "Das Benzin Mega Guitar Diezel VH4 (mega chanel) (mono)"),
        "cd01381a40": HelixModelInfo(category: "Amp+Cab", name: "Cali IV Lead Guitar MESA/Boogie Mark IV (lead channel)  (mono)"),
        "cd01421a40": HelixModelInfo(category: "Amp+Cab", name: "Line 6 2204 Mod Guitar Line 6 Original  (mono)"),
        "cd01481a40": HelixModelInfo(category: "Amp+Cab", name: "Line 6 Fatality Guitar Line 6 Original  (mono)"),
        "cd014f1a40": HelixModelInfo(category: "Amp+Cab", name: "Archetype Clean Guitar Paul Reed Smith Archon (clean channel)  (mono)"),
        "cd01501a40": HelixModelInfo(category: "Amp+Cab", name: "Archetype Lead Guitar Paul Reed Smith Archon (lead channel)  (mono)"),
        "cd01531a31": HelixModelInfo(category: "Amp+Cab", name: "Line 6 Litigator Guitar Line 6 Original  (mono)"),
        "cd015d1a40": HelixModelInfo(category: "Amp+Cab", name: "Line 6 Badonk Guitar Line 6 Original  (mono)"),
        "cd016b1a4a": HelixModelInfo(category: "Amp+Cab", name: "Busy One Ch1  (mono)"),
        "cd016c1a4a": HelixModelInfo(category: "Amp+Cab", name: "Busy One Ch2  (mono)"),
        "cd016d1a4a": HelixModelInfo(category: "Amp+Cab", name: "Busy One Jump  (mono)"),
        "cd01801a40": HelixModelInfo(category: "Amp+Cab", name: "Derailed Ingrid Guitar Trainwreck Circuits Express  (mono)"),
        "cd018d1a31": HelixModelInfo(category: "Amp+Cab", name: "Voltage Queen  (mono)"),
        "cd01de1a42": HelixModelInfo(category: "Amp+Cab", name: "Brit Trem Nrm Guitar Marshall JTM-50 (normal channel)  (mono)"),
        "cd01df1a42": HelixModelInfo(category: "Amp+Cab", name: "Brit Trem Brt Guitar Marshall JTM-50 (bright channel)  (mono)"),
        "cd01e01a42": HelixModelInfo(category: "Amp+Cab", name: "Brit Trem Jump Guitar Marshall JTM-50 (jumped)  (mono)"),
        "cd01e41a46": HelixModelInfo(category: "Amp+Cab", name: "Cartographer Guitar Ben Adrian Cartographer  (mono)"),
        "cd01e61a3b": HelixModelInfo(category: "Amp+Cab", name: "Agua 51  (mono)"),
        "cd01f41a40": HelixModelInfo(category: "Amp+Cab", name: "Placater Dirty Guitar Friedman BE-100 (BE/HBE channel)  (mono)"),
        "cd01f61a37": HelixModelInfo(category: "Amp+Cab", name: "Cali Texas Ch2 Guitar MESA/Boogie Lone Star (drive channel)  (mono)"),
        "cd02001a40": HelixModelInfo(category: "Amp+Cab", name: "Placater Clean Guitar Friedman BE-100 (clean channel)  (mono)"),
        "cd02021a37": HelixModelInfo(category: "Amp+Cab", name: "Cali Texas Ch1 Guitar MESA/Boogie Lone Star (clean channel)  (mono)"),
        "cd02071a4a": HelixModelInfo(category: "Amp+Cab", name: "Ampeg SVT-4 PRO  (mono)"),
        "cd02211a40": HelixModelInfo(category: "Amp+Cab", name: "Revv Gen Red Guitar Revv Generator 120 (red/high gain ch. 4)  (mono)"),
        "cd02311a40": HelixModelInfo(category: "Amp+Cab", name: "Revv Gen Purple Guitar Revv Generator 120 (purple/gain ch. 3)  (mono)"),
        "cd02571a40": HelixModelInfo(category: "Amp+Cab", name: "Das Benzin Lead Guitar Diezel VH4 (lead chanel)  (mono)"),
        "cd02591a40": HelixModelInfo(category: "Amp+Cab", name: "Das Benzin Mega Guitar Diezel VH4 (mega chanel)  (mono)"),
        "cd01321acd0167": HelixModelInfo(category: "Amp+Cab", name: "Matchstick Ch1 Guitar Matchless DC30 (channel 1)  (mono)"),
        "cd01331acd0166": HelixModelInfo(category: "Amp+Cab", name: "Matchstick Ch2 Guitar Matchless DC30 (channel 2)  (mono)"),
        "cd01341acd0166": HelixModelInfo(category: "Amp+Cab", name: "Matchstick Jump Guitar Matchless DC30 (jumped)  (mono)"),
        "cd01391acd0164": HelixModelInfo(category: "Amp+Cab", name: "Cali IV Rhythm 1 Guitar MESA/Boogie Mark IV (channel I)  (mono)"),
        "cd013a1acd0164": HelixModelInfo(category: "Amp+Cab", name: "Cali IV Rhythm 2 Guitar MESA/Boogie Mark IV (channel II)  (mono)"),
        "cd01571acd0165": HelixModelInfo(category: "Amp+Cab", name: "Del Sol 300  (mono)"),
        "cd015e1acd016e": HelixModelInfo(category: "Amp+Cab", name: "Woody Blue  (mono)"),
        "cd02151acd0228": HelixModelInfo(category: "Amp+Cab", name: "GrammaticoLG Brt (mono)"),
        "cd02161acd0228": HelixModelInfo(category: "Amp+Cab", name: "GrammaticoLG Jmp (mono)"),
        "cd02171acd0228": HelixModelInfo(category: "Amp+Cab", name: "GrammaticoLG Nrm (mono)"),
        "cd021b1acd0227": HelixModelInfo(category: "Amp+Cab", name: "Fullerton Brt  (mono)"),
        "cd021c1acd0227": HelixModelInfo(category: "Amp+Cab", name: "Fullerton Jump  (mono)"),
        "cd021d1acd0227": HelixModelInfo(category: "Amp+Cab", name: "Fullerton Nrm  (mono)"),
        "cd024f1acd024d": HelixModelInfo(category: "Amp+Cab", name: "US Princess  (mono)"),
    ]

    static func lookup(_ id: String) -> HelixModelInfo? {
        models[id.lowercased()]
    }
}
